codeTrial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('coderunner.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

coderunner/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from . import views
from .forms import LoginForm, CustomPasswordResetForm, CustomPasswordChangeForm
from .views import APP

app_name = 'coderunner'

# Authentication system URLs
urlpatterns = [
    path('accounts/login/',
         auth_views.LoginView.as_view(authentication_form=LoginForm,
                                      redirect_authenticated_user=True,
                                      extra_context={'app': APP,
                                                     'title': 'Sign in'}),
         name='login'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/signup/account_activation_sent/',
         views.account_activation_sent, name='account_activation_sent'),
    path('activate/<uidb64>/<token>/',
         views.activate, name='activate'),
    path('accounts/password_reset/',
         auth_views.PasswordResetView.as_view(extra_context={'app': APP})),
    path('accounts/password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(extra_context={
                                                  'app': APP})),
    path('accounts/reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             form_class=CustomPasswordResetForm, extra_context={
                 'app': APP})),
    path('accounts/reset/done/',
         auth_views.PasswordResetCompleteView.as_view(extra_context={
                                                      'app': APP})),
    path('accounts/password_change/',
         auth_views.PasswordChangeView.as_view(
             form_class=CustomPasswordChangeForm,
             extra_context={'app': APP})),
    path('accounts/password_change/done/',
         auth_views.PasswordChangeDoneView.as_view(extra_context={
                                                   'app': APP})),
]

urlpatterns = urlpatterns + [
    path('', views.index, name='index'),
]

# Enforce Login required on the below URLs
urlpatterns = urlpatterns + [
    path('home/', login_required(views.home), name='home'),
    path('details/<int:qid>/', login_required(views.details), name='details'),
    path('publish_question/', views.publish_question, name='publish_question'),
    path('publish_question/modify/<pk>/',
         views.ModifyQuestion.as_view(extra_context={'app': APP}),
         name='modify_question'),
    path('publish_question/delete/<pk>/',
         views.DeleteQuestion.as_view(extra_context={'app': APP}),
         name='delete_question'),
    path('program/<int:qid>/', login_required(views.program), name='program'),
    path('ajax/run_code/<int:qid>/',
         login_required(views.run_code), name='run_code'),
    path('ajax/validate_program/',
         login_required(views.validate_program), name='validate_program')
]

coderunner/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MinValueValidator


# Create your models here.
class Questions(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    published_on = models.DateTimeField(auto_now_add=True)
    question_text = models.CharField(max_length=200)
    question_desc = models.CharField(max_length=500)
    pre_code_snippet = models.TextField()
    output_format = models.CharField(max_length=500)

    # Set time out for the question
    # [User code must return output by this time]
    # Default is 5 sec (set to 0 for None)
    timeout = models.IntegerField(default=5, validators=[MinValueValidator(0)])

    # one testcase to validate the user code when Run button is pressed
    run_testcase1_input = models.TextField(max_length=50)
    run_testcase1_output = models.TextField()

    # Two testcases to validate user submission
    submit_testcase1_input = models.TextField(max_length=50)
    submit_testcase1_output = models.TextField()
    submit_testcase2_input = models.TextField(max_length=50)
    submit_testcase2_output = models.TextField()
    times_submitted = models.IntegerField(default=0)
    # To track number of times the question answered correctly
    times_correct = models.IntegerField(default=0)
    # To track number of times the question answered wrongly
    times_wrong = models.IntegerField(default=0)
    score = models.IntegerField(default=10,
                                validators=[MinValueValidator(5)])

    class Meta:
        verbose_name = 'Questions'
        verbose_name_plural = 'Questions'

    def __str__(self):
        return self.question_text


class Submissions(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    submitted_on = models.DateTimeField(auto_now_add=True)
    submitted_snippet = models.TextField()
    question = models.ForeignKey(Questions, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Submissions'
        verbose_name_plural = 'Submissions'

    def __str__(self):
        return (str(self.username) + '@ [' + str(self.question) + ']')


class UserProfile(models.Model):
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    score = models.IntegerField(default=0,
                                validators=[MinValueValidator(0)])

    class Meta:
        verbose_name = "UserProfile"
        verbose_name_plural = "UserProfiles"

    def __str__(self):
        return str(self.username)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(username=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

coderunner/views.py
import os

from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User, Permission
from django.contrib.auth.decorators import user_passes_test
from django.views.generic.edit import UpdateView, DeleteView

from .models import Questions, Submissions
from .forms import SignUpForm, PublishQuestionForm
from .tokens import account_activation_token

import subprocess as sp
from datetime import datetime
from pylint import epylint as lint

import logging

logger = logging.getLogger(__name__)
APP_NAME = "CODERUNNER"
LOGO = ' '.join(list(APP_NAME))
APP = {'name': APP_NAME, 'logo': LOGO, 'title': None}
FILE_DIR = "/tmp/coderunner_"
FILE_EXT = ".py"
REQ_SCORE_TO_PUBLISH = 20

try:
    CAN_PUBLISH_QUESTION = {
        'perm_obj': Permission.objects.get(name='Can add Questions'),
        'string': 'coderunner.add_questions'
    }
except Exception as e:
    logger.error(e)


# Create your views here.
def signup(request):
    """Extend the basic UserCreationForm to accept email
    by using the custom SignUpForm
    and confirm the email address using an activation link
    """

    # Set the title of the webpage
    APP['title'] = 'Sign up'

    if request.user.is_authenticated:
        return redirect('/home')

    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            if user.is_active:
                logger.warning(f'{user.username} is set '
                               'to active before checking activation token')
            current_site = get_current_site(request)
            email_subject = 'Activate your CodeRunner account'
            email_message = render_to_string(
                'registration/account_activation_email.html', {
                    'user': user,
                    'domain': current_site.domain,
                    # Decode the base64 encoded data before sending,
                    # else the byte code will be wrapped with str obj
                    # which can't be decoded further
                    'uid': urlsafe_base64_encode(
                        force_bytes(user.pk)).decode(),
                    'token': account_activation_token.make_token(user)
                })
            logger.info('Account activation link '
                        f'has been sent to {request.user}')
            user.email_user(email_subject, email_message)
            return redirect('/accounts/signup/account_activation_sent')
    else:
        form = SignUpForm()
    return render(request,
                  'registration/signup.html',
                  {'form': form, 'app': APP})


def activate(request, uidb64, token):
    """View to handle the activation
    process of a new user account"""

    # Try to decode the UID from the activation
    # URL and check if UID exists in the database

    APP['title'] = 'Account activation'
    try:
        uid = urlsafe_base64_decode(uidb64.encode())
        user = User.objects.get(pk=uid)
        if user.is_active:
            logger.warning(f'Account: {user.username} is already active!')
            reasons = ['Account is already active', ]
            return render(request,
                          'registration/account_activation_invalid.html',
                          {'reasons': reasons, 'app': APP})
    except User.DoesNotExist:
        logger.warning(f'Account: {user.username} has not been created yet!')
        reasons = ['Account not found', ]
        return render(request,
                      'registration/account_activation_invalid.html',
                      {'reasons': reasons, 'app': APP})
    except (TypeError, ValueError, OverflowError) as e:
        raise e

    # If user is found at the UID, check the
    # token. Upon successful token validation
    # activate the user account, authenticate
    # the user and redirect to the home page
    if user is not None:
        if account_activation_token.check_token(user, token):
            user.is_active = True
            user.save()
            auth_login(request, user)
            return redirect('/home')
        else:
            logger.warning('Token tampering '
                           f'detected for Account: {user.username}')
            reasons = ['Token validation failed', ]
            return render(request,
                          'registration/account_activation_invalid.html',
                          {'reasons': reasons, 'app': APP})
    else:
        reasons = ['Account not found', ]
        return render(request,
                      'registration/account_activation_invalid.html',
                      {'reasons': reasons, 'app': APP})


def account_activation_sent(request):
    """After successfully sending the
    account activation link, render this web page
    """
    return render(request,
                  'registration/account_activation_sent.html',
                  {'app': APP})


def index(request):
    logger.debug(f'{request.user} is accessing index page')
    return redirect('/home/')


def home(request):
    """Return welcome message with listing
    all available questions to appear
    """

    APP['title'] = 'H O M E'
    user = request.user
    if user.has_perm(CAN_PUBLISH_QUESTION['string']):
        publish_perm = True
    else:
        publish_perm = False

    # Returns empty QuerySet if username
    # does not exist or match with any of the submissions
    submissions = Submissions.objects.filter(
        username__username=user)

    questions = Questions.objects.order_by('-id')[:5]

    return render(request, 'coderunner/index.html',
                  {'questions': questions,
                   'submissions': submissions,
                   'user': user,
                   'publish_perm': publish_perm,
                   'app': APP})


@user_passes_test(lambda u: u.has_perm(CAN_PUBLISH_QUESTION['string']),
                  login_url='/home/')
def publish_question(request):
    """View to publish a question
    Before accessing the view do check
    if the user has minimum score """

    form = PublishQuestionForm(request.POST or None)
    if form.is_valid():
        publish = form.save(commit=False)

        # Save the authenticated user
        # as the author of the question
        publish.author = request.user

        publish.save()
        return redirect('/home/')
    return render(request,
                  'coderunner/publish_question.html',
                  {'form': form, 'app': APP})


def check_authorization(request, qid_obj):
    """ Check if the user is
    authorized to modify the question,
    by verifying if the requesting user
    is the author of the question

    :param qid_obj:     Questions object
    :return True:       If user is authorized
    :return False:      User is unauthorized

    """
    logger.debug(f'Checking authorization for user {request.user}')
    if request.user == qid_obj.author:
        return True
    else:
        return False


class ModifyQuestion(UpdateView):
    """ View to allow the author of
    the question to modify the question
    """

    model = Questions
    template_name = 'coderunner/modify_question.html'
    form_class = PublishQuestionForm
    success_url = '/home/'

    def dispatch(self, request, *args, **kwargs):
        """Override the dispatch method
        to check if the requesting user
        is authorized to modify the question
        """

        qid_obj = get_object_or_404(Questions, pk=kwargs.get('pk', None))
        if not check_authorization(request, qid_obj):
            logger.debug(f'{request.user} is not '
                         f'authorized to modify {qid_obj.question_text}')
            return redirect('/home/')
        else:
            logger.debug(f'{request.user} is authorized '
                         f'to modify {qid_obj.question_text}')
            return super().dispatch(request, *args, **kwargs)


class DeleteQuestion(DeleteView):
    """Generic class based view to implement
    delete fucntionalities for the created objects
    Before rendering the view do check if the user
    is authorized to delete the object
    """

    model = Questions
    success_url = '/home/'

    def dispatch(self, request, *args, **kwargs):
        qid_obj = get_object_or_404(Questions, pk=kwargs.get('pk', None))
        if not check_authorization(request, qid_obj):
            logger.debug(f'{request.user} is not '
                         f'authorized to delete {qid_obj.question_text}')
            return redirect('/home/')
        else:
            logger.debug(f'{request.user} is authorized '
                         f'to delete {qid_obj.question_text}')
            return super().dispatch(request, *args, **kwargs)


@csrf_exempt
def validate_program(request):
    """
    Handles AJAX calls for realtime code linting event
    """

    # Track the frequency of the event
    # occurance and display it on STDOUT
    request.session['event_count'] += 1
    logger.debug(f"Event occurance: {request.session['event_count']} times")

    # Get the code snippet from the POST data
    snippet = request.POST.get('snippet', '')

    # SLOW DOWN THE LINTING PROCESS to save system resources:
    # If Linting_event_occurance_interval < 1 sec,
    # then don't process the snippet for linting
    # and update "last_event_time"
    # (Reduced the interval to 1 from 5 for realtime linting)
    if (datetime.timestamp(datetime.now()) -
            request.session['last_event_time']) < 1:

coderunner/templates/coderunner/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <title>
    {% if title %}
        {{ title }}
    {% elif app.title %}
        {{ app.title }}
    {% else %}
        {{ app.logo }}
    {% endif %}
  </title>

    <link rel="stylesheet" type="text/css" href="{% static "coderunner/css/style.css" %}">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block header %}
        
    {% endblock header %}
</head>

<body class='theme'>
    {# Holder of Header, content[body] and footer divs #}
    <div id='holder'>
        {# Header #}
        <header>
            <div id="logo">{{app.logo}}</div>
            <div id='user-tools'>
                {% if user.is_authenticated %}
                    Welcome,
                    <strong>{{ user.username }}</strong>
                    .
                    <a href="{% url 'coderunner:home' %}">
                        <i class="fa fa-home" style="font-size: 16px"></i>
                    </a>
                    {% if publish_perm %}
                    .
                        <a href="{% url 'coderunner:publish_question' %}">Publish</a>
                    {% endif %}
                    .
                    <a href="{% url 'password_change' %}">Change password</a>
                    /
                    <a href="{% url 'logout' %}">
                        <span class="glyphicon glyphicon-log-out"></span> Logout
                    </a>
                {% else %}
                    <a href="{% url 'login' %}">Login</a>
                    or
                    <a href="{% url 'coderunner:signup' %}">Signup</a>
                {% endif %}
            </div>
        </header>

        {# Body #}
        <div id="content">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% block content %}
                
            {% endblock content %}
        </div>

        {# Footer #}
        <footer>
            <a href="https://www.github.com/AyushSenapati/CodeRunner">
                <i class="fa fa-github" style="font-size: 25px; padding-top:20px;"></i>
            </a>
            <p style="padding-top:5px;">
                <i class="fa fa-copyright" style="font-size:11px;"></i>
                 Copy right 2018, 
                 <strong>
                    {{ app.logo }} <i class="fa fa-code" style="font-size: 12px;"></i>
                </strong>
                <br>
                Powered by <strong>Django</strong>
            </p>
        </footer>

    </div>
</body>
</html>

coderunner/templates/coderunner/details.html
{% extends "coderunner/base.html" %}
{% load staticfiles %}

{% block header %}
    <script type="text/javascript" src="{% static 'coderunner/codemirror/js/jquery.min.js' %}">
    </script>
    <script src="{% static 'coderunner/codemirror/plugins/lib/codemirror.js' %}"></script>
    <link rel="stylesheet" href="{% static 'coderunner/codemirror/plugins/lib/codemirror.css' %}">
    <link rel="stylesheet" href="{% static 'coderunner/codemirror/plugins/theme/neo.css' %}">
    <link rel="stylesheet" href="{% static 'coderunner/codemirror/plugins/addon/display/fullscreen.css' %}">
    <script src="{% static 'coderunner/codemirror/plugins/addon/display/fullscreen.js' %}"></script>
    <script src="{% static 'coderunner/codemirror/plugins/mode/python/python.js' %}"></script>

{% endblock header %}


{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-9" style="padding-top: 35px;">

            <p class="heading">Question</p>
             <div class='shadow no-textarea'>
                <p>{{ question.question_text }}</p>
                <p class="heading">Description</p>
                <p><i>{{ question.question_desc }}</i></p>
                <p class="heading">Output format</p>
                <p>{{ question.output_format }}</p>
            </div>

            <div style="height: 40px;"></div>

            <div id='form' >
                <form action="{% url 'coderunner:program' question.id %}" method="post">
                    {% csrf_token %}
                    <div class='shadow'>
<textarea name="program" id="id_code_editor" style="border: none;">
{{ question.pre_code_snippet}}
</textarea>
- Press Esc to toggle full screen
                    </div>
                    <br>
                    <div style="float: right;">
                        <button type="button" name="button" class="btn btn-secodary" id="run">
                            Run
                        </button>
                        &nbsp;&nbsp;
                        <input type="submit" name="button" class="btn btn-primary" value="Submit">
                    </div>
                </form>
            </div>
            
            <br><br>
            <div>
                <p class="heading">Result</h3>
                <div class="shadow">
<textarea id='id_result_area' style="border: none">
</textarea>
                </div>
            </div>
        
        </div>
 
        <!-- Question details section-->
        <div class="col-lg-3">
            <div id="content-related">
                <div class='shadow_detail'>
                    <p class="heading">Question details</p>
                    <div>
                        Author: 
                        <div style="position: relative;float: right;">
                            {{ question.author }}
                        </div>
                    </div>
                    {# <br> #}
                    <div>
                        Submitted: 
                        <div style="position: relative;float: right;">
                            {{ question.times_submitted }} time(s)
                        </div>
                    </div>
                    <div>
                        Pass percentage:
                        <div style="position: relative;float: right;">
                            {{ pass_percent }} %
                        </div>
                    </div>
                    <div>
                        Award:
                        <div style="position: relative;float: right;">
                            {{ question.score }} points
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End of question details section-->

    </div>
</div>

{# CodeMirror - code editor instance #}
<script type="text/javascript">
    var editor = CodeMirror.fromTextArea(document.getElementById('id_code_editor'), {
        lineNumbers: true,
        mode: "python",
        indentUnit: 4,
        tabSize: 4,
        lineWrapping: true,
        // readOnly: "nocursor",
        theme: "neo",
        extraKeys: {
            "Tab": "indentAuto",
            "Esc": function(cm) {
            if (cm.getOption("fullScreen")) cm.setOption("fullScreen", false);
            else cm.setOption("fullScreen", true);
        }},

    });
</script>

{# CodeMirror - result textarea instance #}
<script type="text/javascript">
    var result_area = CodeMirror.fromTextArea(document.getElementById('id_result_area'), {
        lineWrapping: true,
        readOnly: "nocursor",
        theme: "neo",
    });
</script>

{# Ajax call for running the code #}
<script type="text/javascript">
    $("#run").click(function () {
        var snippet = editor.getValue();

        $.ajax({
            type: 'POST',
            url: "{% url 'coderunner:run_code' question.id %}",
            data: {
                'snippet': snippet
            },
            dataType: 'json',
            success: function(data) {
                if (data){
                    var disp = '';
                    for ( var index in data.output ) {
                        disp += data.output[index] + '\n';
                    }
                    result_area.getDoc().setValue(disp);
                }
            }
        });
    });
</script>

{# Ajax call for linting #}
<script>
    editor.on("change", function () {
        var snippet = editor.getValue()

        $.ajax({
            type: 'POST',
            url: '{% url "coderunner:validate_program" %}',
            data: {
                'snippet': snippet
            },
            dataType: 'json',
            success: function(data) {
                if (data){
                    var disp = '';
                    for ( var key in data ) {
                        disp += "Line Number: " +
                            data[key].line_num + '   Error Message: ' +
                            data[key].error_message + '\n';
                    }
                    result_area.getDoc().setValue(disp);
                }
                else {
                    result_area.getDoc().setValue("Linting: success");
                }
            }
        });
    });
</script>

{% endblock content %}

coderunner/templates/coderunner/index.html
{% extends "coderunner/base.html" %}


{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-9" style="padding-top: 35px;">
            <p class="heading">Latest published questions</p>
            {% if questions %}
            {% for question in questions %}
                <div class="shadow no-textarea popout">
                    <div class="col-lg-10" style="font-size:10px">
                        <p style="font-size:16px">{{ question.question_text }}</p>
                            Author: {{ question.author.username }}
                            /
                            Posted on: {{ question.published_on }}
                            / 
                        {% if question.times_submitted > 0 %}
                            Submitted {{ question.times_submitted }} time(s)
                        {% else %}
                            Be the first to submit a solution
                        {% endif %}
                    </div>

                    <div class="col-lg-2">
                        {% if user.username == question.author.username %}
                            <a href="{% url 'coderunner:modify_question' question.id %}" style="color: #002659;">
                                <button class="btn">M o d i f y</button>
                            </a>
                        {% else %}
                            <a href="{% url 'coderunner:details' question.id %}" style="color: #002659;">
                                <button class="btn">S o l v e</button>
                            </a>
                        {% endif %}
                    </div>
                </div> 
            {% endfor %}
            {% endif %}
        </div>

        <div class="col-lg-3">
            <div id="content-related">
                <div class='shadow_detail'>
                    <p class="heading">User details</p>
                    {# <br> #}
                    <div>
                        Date joined:
                        <div style="position: relative;float: right;">
                            {{ user.date_joined.date }}
                        </div>
                    </div>
                    {# <br> #}
                    <div>
                        Last login:
                        <div style="position: relative;float: right;">
                            {{ user.last_login.date }}
                        </div>
                    </div>
                    {# <br> #}
                    <div>
                        Problems solved:
                        <div style="position: relative;float: right;">
                            {{ submissions|length }}
                        </div>
                    </div>
                    <div>
                        Score:
                        <div style="position: relative;float: right;">
                            {{ user.userprofile.score }}
                        </div>
                    </div>
                    <div>
                        Can I publish:
                        <div style="position: relative;float: right;">
                            {% if publish_perm %}
                                Yes
                            {% else %}
                                No
                                <a href="#" title="After scoring 20 Publish button will appear automatically">
                                    <i class="fa fa-info-circle"></i>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

{% endblock content %}

coderunner/templates/coderunner/modify_question.html
{% extends "coderunner/base.html" %}

{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8" style="padding-top: 35px;">
            <p class="heading">Update the Question</p>
            <form action="" method="post">
                <div class="shadow" style="padding: 35px;">
                    {% csrf_token %}

                    {{ form.as_p }}
                </div>
                <br>
                <div style="float: right;">
                    <button class="btn btn-primary">UPDATE</button>
                </div>
            </form>
            <a href="{% url 'coderunner:delete_question' object.id %}">
                <button class="btn" style="background: darkred; color: white;">
                    <i class="fa fa-trash-o" style="font-size: 16px"></i> DELETE
                </button>
            </a>
        </div>
        <div class="col-lg-2"></div>
    </div>
</div>

{% endblock content %}

coderunner/templates/coderunner/questions_confirm_delete.html
{% extends "coderunner/base.html" %}

{% block content %}
    <div class="container-fluid">
    <div class="row">
        <div class="col-lg-2"></div>
        <div class="col-lg-8" style="padding-top: 35px;">
            <p class="heading">Confirmation</p>
            <form action="" method="post">
                <div class="shadow" style="padding: 35px;">
                    {% csrf_token %}

                    <p>Are you sure you want to delete "{{object}}" ?</p>
                </div>
                <br>
                <div style="float: right;">
                    <button class="btn btn-primary">Yes</button>
                </div>
            </form>
            <a href="{% url 'coderunner:home'%}">
                <button class="btn" style="background: darkred; color: white;">Cancel</button>
            </a>
        </div>
        <div class="col-lg-2"></div>
    </div>
</div>

{% endblock content %}